schema = 1
name = "rust-itertools"
revision = 1
provides = [
  "rust.callable-signatures",
  "rust.library-behaviors",
]
requires = ["rust.syntax-tree"]

[[contents]]
path = "api/itertools-0.15.0.json"
kind = "callable-signatures"
media-type = "application/vnd.infact.external-catalog.v1+json"
sha256 = "sha256:0c51e2a3559dc0a33e1f1781269a0024d0f7fbbda7301a33f9f2fa101c552d45"

[[contents]]
path = "behaviors/itertools-counts-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:2a75654c95d569e5a98a618944cd1b910e77c310afb7b95ddc555bf01f1ab595"

[[contents]]
path = "behaviors/itertools-counts-by-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:a7ab72cd28d19cdda5e860582e211d35ce44b00f78ae7157e4a9912cbd1ce630"

[[contents]]
path = "behaviors/itertools-into-group-map-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:9efff0413a83acbb2b334a45a5208e4b9b652530a126bfedfa0cccc83065110c"

[[contents]]
path = "behaviors/itertools-into-group-map-by-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:59a654c69f455d58c03b3a4a72b5a07b7e652cae4aca93ad4d018e8ac88e6472"

[[contents]]
path = "behaviors/itertools-sorted-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:c25089d55bfc49ba4c918338d7f6113ce4ada0c95ceda34bf93e0d953b4e92d7"

[[contents]]
path = "behaviors/itertools-sorted-by-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:feed5d43b66329f27a8d59253fbe2745345208433f2edc0b071bc999b2418385"

[[contents]]
path = "behaviors/itertools-sorted-by-key-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:9d1c218d42306920dfbc3d749dab74c3133abc6e470fc17f9972b3fb140d449d"

[[contents]]
path = "behaviors/itertools-sorted-unstable-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:1159e92370412a932d2863c4026407a3e7eccb42a34b2370681b6bb709f1f0ca"

[[contents]]
path = "behaviors/itertools-sorted-unstable-by-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:d448ff53be3f9fb6b9c220a9f6d68f04e6c7a213f2fa82648706d20769933c40"

[[contents]]
path = "behaviors/itertools-sorted-unstable-by-key-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:9d87e61ae9f3a2e3a93904c37713c1cae4637f1a4c9e2adc0d2daf9f60f3f246"

[subject]
kind = "library"
language = "rust"
ecosystem = "cargo"
name = "itertools"
version = "0.15.0"

[[sources]]
kind = "package"
name = "itertools"
version = "0.15.0"
sha256 = "sha256:9d87e61ae9f3a2e3a93904c37713c1cae4637f1a4c9e2adc0d2daf9f60f3f246"

[derivation]
generator = "infact"
generator-version = "0.0.0"
analyzer-sha256 = "sha256:9d87e61ae9f3a2e3a93904c37713c1cae4637f1a4c9e2adc0d2daf9f60f3f246"
