[package]
name = "infact-rust-lower"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "A faithful Rust syntax tree that lifts from source and prints back to it."

[dependencies]
entl-tree-sitter.workspace = true
tree-sitter.workspace = true

[dev-dependencies]
entl-tree-sitter.workspace = true

[lints]
workspace = true
