schema = 1
name = "rust-itertools"
revision = 1
provides = [
  "rust.callable-signatures",
  "rust.library-behaviors",
]
requires = ["rust.syntax-tree"]

[[contents]]
path = "api/itertools-0.15.0.json"
kind = "callable-signatures"
media-type = "application/vnd.infact.external-catalog.v1+json"
sha256 = "sha256:0c51e2a3559dc0a33e1f1781269a0024d0f7fbbda7301a33f9f2fa101c552d45"

[[contents]]
path = "behaviors/itertools-counts-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:3cfea3deab2b0ab068bb0c48c8d1a8d4032a37c94cf76a03334ee2c10a359d2a"

[[contents]]
path = "behaviors/itertools-counts-by-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:dd51356d8345967b5256f92c45979f1be95b4453314d9d08259317847d637ba8"

[[contents]]
path = "behaviors/itertools-into-group-map-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:1e4539938cd27dd66127d9be45c5b9151a7fe79509c7fe6e7b4e920c25163c5d"

[[contents]]
path = "behaviors/itertools-into-group-map-by-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:81a8b936ea38a2812881f5d287e93cc994d8ac74eefea882ca3c43fbebec33c6"

[[contents]]
path = "behaviors/itertools-sorted-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:0b9adf6c70f2f7ead8cd677c54553a9bc5be69841eef6559b5a1de859a7c71f2"

[[contents]]
path = "behaviors/itertools-sorted-by-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:e290028308ad2575415420f75cc8f7e79f4a7d284a634e40990c64e1d93be0bf"

[[contents]]
path = "behaviors/itertools-sorted-by-key-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:86ec9cdb0c914e54ecb81ff44b0f4ccda1e4ad7b9c39715ca0c7fce021bb7f6f"

[[contents]]
path = "behaviors/itertools-sorted-unstable-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:a5d9015944d68fda7f2cd03c54a0929e69452789365c29aba3e9b1693ad93cd3"

[[contents]]
path = "behaviors/itertools-sorted-unstable-by-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:2c24e44f7bd8d67e24e3b6f8b320d123af54c59290752436cafe94d86ee84eb4"

[[contents]]
path = "behaviors/itertools-sorted-unstable-by-key-0.15.0.json"
kind = "library-behavior"
media-type = "application/vnd.infact.library-behavior.v1+json"
sha256 = "sha256:f09cbf9bdedbd07bc21e57d4a14d7199f4b143dd77c2737e96b95729e681e56f"

[subject]
kind = "library"
language = "rust"
ecosystem = "cargo"
name = "itertools"
version = "0.15.0"

[[sources]]
kind = "package"
name = "itertools"
version = "0.15.0"
sha256 = "sha256:8b4baf93f58d4425749ca49a51c50ebab072c5df6994d08fed93541c331481dc"

[derivation]
generator = "infact"
generator-version = "0.0.0"
analyzer-sha256 = "sha256:5f8f5a19584e8394170a99e1b18979a05011dea0a3fed15e0c33f127962e5d98"
